### ISSUE TITLE
documentclass 'chapter'

### ISSUE THREAD

**Issue by murphyp228** [GR8DAN/coventry-thesis#2]
Hi @GR8DAN , Help need rather than an issue. 

Thanks for creating this template, under documentclass you mention:

% 'chapter' : This option enables only the specified chapter and it's references
%  Useful for review and corrections.

May i  check:

If i run typeset against  : \documentclass[a4paper,11pt,times,print,index,draft]{Classes/CUPhDThesis} - it works perfectly

If i run typeset against  : \documentclass[a4paper,11pt,times,print,index,draft,chapter1]{Classes/CUPhDThesis} - i get all chapters as above.

If i run typeset against  : \documentclass[a4paper,11pt,times,print,index,draft,chapter]{Classes/CUPhDThesis} - only chapter 3 shows

Am i missing anything?

Cheers
Paul

**Comment by murphyp228** [comment]
Sorted 

Sorry found the reference to chapter 3.

**Comment by GR8DAN** [comment]
Thanks for letting me know you sorted the problem.
